import { test } from "node:test";
import assert from "node:assert/strict";
import { traceToSteps } from "../src/core/exec-tracer-model.ts";
import type { ExecTrace } from "../src/core/exec-tracer-model.ts";
import { DEFAULT_TRACE_NARRATION, resolveNarration } from "../src/core/trace-narration.ts";
import type { TraceNarration } from "../src/core/trace-narration.ts";
import { placeholdersOf } from "../src/core/template.ts";

// test/trace-narration.test.ts - the captions under a traced program.
//
// WHY THIS EXISTS
// These sentences are GENERATED by the adapter, not authored in a lesson, so
// before this seam existed they could not be translated at all - a Spanish lesson
// would have shown a Spanish page narrating itself in English. Two things have to
// stay true: English callers must see byte-identical output (nobody asked for the
// existing lessons to change), and a translated caller must get NO English left.

/** Two cats: a constructor with a parameter, a field set, an instance call that
 *  prints, and a second instance - the shapes the object-model lessons care
 *  about, exercised through one trace.
 *
 *  The last `WriteLine` sits in `Main` on its own statement on purpose. A print
 *  on the FIRST statement of a method shares its step with the call that pushed
 *  the frame, and the call is the more salient event, so the caption says
 *  "Called ..." and the printing caption never fires. Only a print that is not a
 *  method's opening statement exercises `printed`. */
const TWO_CATS: ExecTrace = {
  code: [
    "class Cat",                                         // 1
    "{",                                                 // 2
    "    private string _name;",                         // 3
    "    public Cat(string name) { _name = name; }",     // 4
    "    public void Speak()",                           // 5
    "    {",                                             // 6
    "        System.Console.WriteLine(_name);",          // 7
    "    }",                                             // 8
    "}",                                                 // 9
    "class Program",                                     // 10
    "{",                                                 // 11
    "    static void Main()",                            // 12
    "    {",                                             // 13
    "        Cat a = new Cat(\"Ada\");",                 // 14
    "        Cat b = new Cat(\"Bo\");",                  // 15
    "        a.Speak();",                                // 16
    "        System.Console.WriteLine(\"done\");",       // 17
    "    }",                                             // 18
    "}",                                                 // 19
  ],
  steps: [
    { line: 14, frames: [{ id: "f0", name: "Main", kind: "entry", vars: [] }], heap: [] },
    {
      line: 4,
      frames: [
        { id: "f0", name: "Main", kind: "entry", line: 14, vars: [] },
        { id: "f1", name: "new Cat", kind: "ctor", vars: [{ name: "name", value: "\"Ada\"" }] },
      ],
      heap: [{ id: "o1", type: "Cat", no: 1, fields: [["_name", "null"]] }],
    },
    {
      line: 14,
      frames: [{ id: "f0", name: "Main", kind: "entry", vars: [{ name: "a", ref: "o1" }] }],
      heap: [{ id: "o1", type: "Cat", no: 1, fields: [["_name", "\"Ada\""]] }],
    },
    {
      line: 15,
      frames: [
        { id: "f0", name: "Main", kind: "entry", vars: [{ name: "a", ref: "o1" }, { name: "b", ref: "o2" }] },
      ],
      heap: [
        { id: "o1", type: "Cat", no: 1, fields: [["_name", "\"Ada\""]] },
        { id: "o2", type: "Cat", no: 2, fields: [["_name", "\"Bo\""]] },
      ],
    },
    {
      line: 7,
      frames: [
        { id: "f0", name: "Main", kind: "entry", line: 16, vars: [{ name: "a", ref: "o1" }, { name: "b", ref: "o2" }] },
        { id: "f2", name: "Speak", kind: "method", recv: "Cat #1", vars: [] },
      ],
      heap: [
        { id: "o1", type: "Cat", no: 1, fields: [["_name", "\"Ada\""]] },
        { id: "o2", type: "Cat", no: 2, fields: [["_name", "\"Bo\""]] },
      ],
      stdout: "Ada\n",
    },
    {
      line: 17,
      frames: [
        { id: "f0", name: "Main", kind: "entry", vars: [{ name: "a", ref: "o1" }, { name: "b", ref: "o2" }] },
      ],
      heap: [
        { id: "o1", type: "Cat", no: 1, fields: [["_name", "\"Ada\""]] },
        { id: "o2", type: "Cat", no: 2, fields: [["_name", "\"Bo\""]] },
      ],
      stdout: "Ada\n",
    },
    {
      line: 17,
      frames: [
        { id: "f0", name: "Main", kind: "entry", vars: [{ name: "a", ref: "o1" }, { name: "b", ref: "o2" }] },
      ],
      heap: [
        { id: "o1", type: "Cat", no: 1, fields: [["_name", "\"Ada\""]] },
        { id: "o2", type: "Cat", no: 2, fields: [["_name", "\"Bo\""]] },
      ],
      stdout: "Ada\ndone\n",
    },
  ],
};

const captions = (trace: ExecTrace, narration?: Partial<TraceNarration>) =>
  traceToSteps(trace, narration).map((s) => s.narr ?? "");

/** The closing beat - the caption after the last statement. */
const lastCaption = (trace: ExecTrace, narration?: Partial<TraceNarration>) => {
  const all = captions(trace, narration);
  return all[all.length - 1];
};

test("no narration argument means the English captions, unchanged", () => {
  const before = captions(TWO_CATS);
  const after = captions(TWO_CATS, undefined);
  assert.deepEqual(after, before);
  // The shapes the object-model lessons rely on are the ones actually generated.
  assert.ok(before.some((c) => c.includes("Called the `Cat` constructor")), before.join(" | "));
  assert.ok(before.some((c) => c.includes("Called `Speak()` on `Cat #1`")), before.join(" | "));
  assert.ok(before.some((c) => c.includes("Printed `done`")), before.join(" | "));
});

test("every default template's slots survive into the rendered caption", () => {
  // A caption built from `calledOn` must actually contain the method and the
  // receiver - i.e. `fill` was handed the vars the template asks for.
  const text = captions(TWO_CATS).join("\n");
  assert.ok(!/\{\w+\}/.test(text), `an unfilled slot reached a caption:\n${text}`);
});

test("a translated set leaves no English in the captions", () => {
  // Drive the translation from the table itself: every key gets a sentinel that
  // keeps its slots. Then EVERY caption must start with a sentinel - because a
  // caption that came from the table can only start with one. A sentence still
  // hardcoded in the adapter would start with a letter instead, which is exactly
  // the bug this seam exists to prevent.
  //
  // Comparing rendered text against the raw English templates does NOT work and
  // must not be reintroduced: a template with a slot ("Entered `{name}`") never
  // appears literally in the output, so that check passes while the caption is
  // hardcoded. It was written that way first, and it missed a real sabotage.
  const translated = {} as Record<string, string>;
  for (const [key, english] of Object.entries(DEFAULT_TRACE_NARRATION)) {
    const slots = placeholdersOf(english).map((p) => `{${p}}`).join(" ");
    translated[key] = `[${key}]${slots ? " " + slots : ""}`;
  }
  const lines = captions(TWO_CATS, translated as Partial<TraceNarration>);
  for (const caption of lines) {
    assert.match(caption, /^\[[a-zA-Z]+\]/, `not from the table: ${caption}\n${lines.join("\n")}`);
  }
  // And the slotless templates, whose English WOULD survive verbatim, are gone.
  const text = lines.join("\n");
  for (const [key, english] of Object.entries(DEFAULT_TRACE_NARRATION)) {
    if (placeholdersOf(english).length) continue;
    assert.ok(!text.includes(english), `English leaked from \`${key}\`: ${english}\n${text}`);
  }
  assert.ok(text.includes("[calledCtor]"), text);
  assert.ok(text.includes("[printed]"), text);
});

test("a truncated run uses the truncated template, not the finished one", () => {
  const cut: ExecTrace = { ...TWO_CATS, truncated: true };
  assert.ok(lastCaption(cut).startsWith("Stopped early"));
  assert.equal(lastCaption(cut, { truncated: "[cut]" }), "[cut]");
});

test("the finished caption counts the printed lines, singular and plural apart", () => {
  assert.equal(lastCaption(TWO_CATS), "The program finished. It printed 2 lines.");

  const oneLine: ExecTrace = {
    ...TWO_CATS,
    steps: TWO_CATS.steps.map((s) => (s.stdout ? { ...s, stdout: "Ada\n" } : s)),
  };
  assert.equal(lastCaption(oneLine), "The program finished. It printed 1 line.");
});

test("a program that printed nothing says so", () => {
  const quiet: ExecTrace = {
    ...TWO_CATS,
    steps: TWO_CATS.steps.map(({ stdout: _stdout, ...rest }) => rest),
  };
  assert.equal(lastCaption(quiet), "The program finished without printing anything.");
});

test("a partial set translates what it carries and keeps English for the rest", () => {
  const text = captions(TWO_CATS, { calledCtor: "[ctor] {type}" }).join("\n");
  assert.ok(text.includes("[ctor] Cat"), text);
  assert.ok(text.includes("Printed `done`"), text);
});

test("an override that DROPPED a slot is refused, not rendered without its value", () => {
  // The whole point: a translation reading "Called the constructor" - with no
  // type in it - must never reach a learner. It falls back to English instead.
  const { narration, issues } = resolveNarration({ calledCtor: "Llamado al constructor" });
  assert.equal(narration.calledCtor, DEFAULT_TRACE_NARRATION.calledCtor);
  assert.deepEqual(issues, [{ key: "calledCtor", missing: ["type"] }]);

  const text = captions(TWO_CATS, { calledCtor: "Llamado al constructor" }).join("\n");
  assert.ok(!text.includes("Llamado al constructor"), text);
  assert.ok(text.includes("Called the `Cat` constructor"), text);
});

test("every default carries the slots its own name implies", () => {
  // Guards the table against a future edit that drops a slot from the ENGLISH
  // side, which would make every translation of it look correct while the
  // English one silently lost a value.
  const expected: Array<[keyof TraceNarration, string[]]> = [
    ["entered", ["name"]],
    ["calledCtor", ["type"]],
    ["calledOn", ["method", "recv"]],
    ["called", ["method"]],
    ["ctorFinishedBack", ["type", "caller"]],
    ["ctorFinished", ["type"]],
    ["returnedTo", ["method", "caller"]],
    ["returned", ["method"]],
    ["printed", ["text"]],
    ["setToNew", ["name", "type"]],
    ["createdNumbered", ["type", "label"]],
    ["created", ["type"]],
    ["pointedAt", ["name", "label"]],
    ["setTo", ["name", "value"]],
    ["runningLine", ["line"]],
    ["finishedPrintedOne", ["n"]],
    ["finishedPrintedMany", ["n"]],
  ];
  for (const [key, slots] of expected) {
    assert.deepEqual(placeholdersOf(DEFAULT_TRACE_NARRATION[key]), slots, key);
  }
});
